# Generated by Django 3.0 on 2021-09-18 07:43

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='帖子名称（CharField）', max_length=225, verbose_name='帖子名称')),
                ('desc', mdeditor.fields.MDTextField(blank=True, verbose_name='帖子内容')),
                ('editedDay', models.DateField(auto_now=True, help_text='编辑日期（DateTimeField）', null=True, verbose_name='编辑日期')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='创建时间（DateTimeField）', null=True, verbose_name='创建时间')),
                ('last_edited_date', models.DateTimeField(auto_now=True, help_text='最后编辑时间（DateTimeField）', null=True, verbose_name='最后编辑时间')),
                ('deleted', models.CharField(choices=[('0', '未删除'), ('1', '已删除')], default='0', help_text='是否删除（CharField，可选值：0，1）', max_length=1, verbose_name='是否删除')),
                ('created_by', models.ForeignKey(blank=True, help_text='创建人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_cb', to='user.UserExtension', verbose_name='创建人ID')),
                ('last_edited_by', models.ForeignKey(blank=True, help_text='最后编辑人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_eb', to='user.UserExtension', verbose_name='最后编辑人ID')),
            ],
            options={
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BlogType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='帖子类型（CharField）', max_length=60, verbose_name='帖子类型')),
                ('color', models.CharField(default='#6190e8', help_text='标签颜色（CharField）', max_length=60, verbose_name='标签颜色')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='创建时间（DateTimeField）', null=True, verbose_name='创建时间')),
                ('last_edited_date', models.DateTimeField(auto_now=True, help_text='最后编辑时间（DateTimeField）', null=True, verbose_name='最后编辑时间')),
                ('deleted', models.CharField(choices=[('0', '未删除'), ('1', '已删除')], default='0', help_text='是否删除（CharField，可选值：0，1）', max_length=1, verbose_name='是否删除')),
                ('created_by', models.ForeignKey(blank=True, help_text='创建人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogt_cb', to='user.UserExtension', verbose_name='创建人ID')),
                ('last_edited_by', models.ForeignKey(blank=True, help_text='最后编辑人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogt_eb', to='user.UserExtension', verbose_name='最后编辑人ID')),
            ],
            options={
                'verbose_name': '帖子类型',
                'verbose_name_plural': '帖子类型',
            },
        ),
        migrations.CreateModel(
            name='Typ2Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='创建时间（DateTimeField）', null=True, verbose_name='创建时间')),
                ('last_edited_date', models.DateTimeField(auto_now=True, help_text='最后编辑时间（DateTimeField）', null=True, verbose_name='最后编辑时间')),
                ('deleted', models.CharField(choices=[('0', '未删除'), ('1', '已删除')], default='0', help_text='是否删除（CharField，可选值：0，1）', max_length=1, verbose_name='是否删除')),
                ('blog', models.ForeignKey(blank=True, help_text='帖子（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Blog', verbose_name='帖子')),
                ('created_by', models.ForeignKey(blank=True, help_text='创建人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typ2blog_cb', to='user.UserExtension', verbose_name='创建人ID')),
                ('last_edited_by', models.ForeignKey(blank=True, help_text='最后编辑人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typ2blog_eb', to='user.UserExtension', verbose_name='最后编辑人ID')),
                ('typ', models.ForeignKey(blank=True, help_text='帖子类别（ForeignKey）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typ', to='blog.BlogType', verbose_name='帖子类别')),
            ],
            options={
                'verbose_name': '帖子类型二联表',
                'verbose_name_plural': '帖子类型二联表',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BlogTalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(help_text='帖子评论（CharField）', max_length=120, verbose_name='帖子评论')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='创建时间（DateTimeField）', null=True, verbose_name='创建时间')),
                ('last_edited_date', models.DateTimeField(auto_now=True, help_text='最后编辑时间（DateTimeField）', null=True, verbose_name='最后编辑时间')),
                ('deleted', models.CharField(choices=[('0', '未删除'), ('1', '已删除')], default='0', help_text='是否删除（CharField，可选值：0，1）', max_length=1, verbose_name='是否删除')),
                ('blog', models.ForeignKey(blank=True, help_text='帖子（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Blog', verbose_name='帖子')),
                ('created_by', models.ForeignKey(blank=True, help_text='创建人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogtalk_cb', to='user.UserExtension', verbose_name='创建人ID')),
                ('last_edited_by', models.ForeignKey(blank=True, help_text='最后编辑人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogtalk_eb', to='user.UserExtension', verbose_name='最后编辑人ID')),
            ],
            options={
                'verbose_name': '帖子类型',
                'verbose_name_plural': '帖子类型',
            },
        ),
    ]
