# Generated by Django 3.0 on 2021-09-24 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210923_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogtags',
            options={'verbose_name': '帖子属性', 'verbose_name_plural': '帖子属性'},
        ),
    ]
