# Generated by Django 3.0 on 2021-09-25 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20210923_0935'),
        ('blog', '0003_auto_20210924_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ForeignKey(blank=True, help_text='封面（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_img', to='files.Images', verbose_name='封面'),
        ),
    ]
