# Generated by Django 3.0 on 2021-09-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210925_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='show',
            field=models.BooleanField(default=True, help_text='是否公开可见', verbose_name='是否公开可见'),
        ),
    ]
