# Generated by Django 3.0 on 2021-10-14 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogcollect_blogpraise'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogtalk',
            options={'verbose_name': '帖子评论', 'verbose_name_plural': '帖子评论'},
        ),
    ]
