# Generated by Django 3.0 on 2021-10-18 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20211014_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogtalk',
            options={'ordering': ['-id'], 'verbose_name': '帖子评论', 'verbose_name_plural': '帖子评论'},
        ),
    ]
