# Generated by Django 3.0 on 2021-10-23 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0007_auto_20211018_1046'),
        ('blog', '0008_auto_20211018_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='trip',
            field=models.ForeignKey(blank=True, help_text='关联行程（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_trip', to='trip.Trip', verbose_name='关联行程'),
        ),
    ]
