# Generated by Django 3.0 on 2021-09-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telcode',
            name='telephone',
            field=models.CharField(blank=True, help_text='电话（CharField）', max_length=20, verbose_name='电话'),
        ),
    ]
