# Generated by Django 3.0 on 2021-09-21 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210918_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='城市名称（CharField）', max_length=225, verbose_name='城市名称')),
                ('wens', models.CharField(help_text='经纬度（CharField）', max_length=225, verbose_name='经纬度')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='创建时间（DateTimeField）', null=True, verbose_name='创建时间')),
                ('last_edited_date', models.DateTimeField(auto_now=True, help_text='最后编辑时间（DateTimeField）', null=True, verbose_name='最后编辑时间')),
                ('deleted', models.CharField(choices=[('0', '未删除'), ('1', '已删除')], default='0', help_text='是否删除（CharField，可选值：0，1）', max_length=1, verbose_name='是否删除')),
                ('created_by', models.ForeignKey(blank=True, help_text='创建人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_cb', to='user.UserExtension', verbose_name='创建人ID')),
                ('last_edited_by', models.ForeignKey(blank=True, help_text='最后编辑人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_eb', to='user.UserExtension', verbose_name='最后编辑人ID')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='userextension',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.City', verbose_name='城市'),
        ),
    ]
