# Generated by Django 3.0 on 2021-09-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210921_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.CharField(blank=True, help_text='所属国家（CharField）', max_length=225, verbose_name='所属国家'),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.CharField(blank=True, help_text='所属省份（CharField）', max_length=225, verbose_name='所属省份'),
        ),
        migrations.AlterField(
            model_name='city',
            name='wens',
            field=models.CharField(blank=True, help_text='经纬度（CharField）', max_length=225, verbose_name='经纬度'),
        ),
    ]
