# Generated by Django 3.0 on 2021-09-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_auto_20210926_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='typ',
            field=models.CharField(blank=True, choices=[('play', '景玩'), ('eat', '餐食'), ('hotel', '住宿'), ('go', '出行')], default='play', help_text='词条分类（CharField，可选值：play,eat,hotel,go）', max_length=10, verbose_name='词条分类'),
        ),
    ]
