# Generated by Django 3.0 on 2021-09-27 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210922_1157'),
        ('place', '0004_place_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_city', to='user.City', verbose_name='城市'),
        ),
    ]
