# Generated by Django 3.0 on 2021-09-27 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210922_1157'),
        ('place', '0005_place_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacePraise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='创建时间（DateTimeField）', null=True, verbose_name='创建时间')),
                ('last_edited_date', models.DateTimeField(auto_now=True, help_text='最后编辑时间（DateTimeField）', null=True, verbose_name='最后编辑时间')),
                ('deleted', models.CharField(choices=[('0', '未删除'), ('1', '已删除')], default='0', help_text='是否删除（CharField，可选值：0，1）', max_length=1, verbose_name='是否删除')),
                ('created_by', models.ForeignKey(blank=True, help_text='创建人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placep_cb', to='user.UserExtension', verbose_name='创建人ID')),
                ('last_edited_by', models.ForeignKey(blank=True, help_text='最后编辑人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placep_eb', to='user.UserExtension', verbose_name='最后编辑人ID')),
                ('place', models.ForeignKey(blank=True, help_text='帖子（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, to='place.Place', verbose_name='帖子')),
            ],
            options={
                'verbose_name': '地点-用户-点赞',
                'verbose_name_plural': '地点-用户-点赞',
                'unique_together': {('place', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='PlaceCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='创建时间（DateTimeField）', null=True, verbose_name='创建时间')),
                ('last_edited_date', models.DateTimeField(auto_now=True, help_text='最后编辑时间（DateTimeField）', null=True, verbose_name='最后编辑时间')),
                ('deleted', models.CharField(choices=[('0', '未删除'), ('1', '已删除')], default='0', help_text='是否删除（CharField，可选值：0，1）', max_length=1, verbose_name='是否删除')),
                ('created_by', models.ForeignKey(blank=True, help_text='创建人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placec_cb', to='user.UserExtension', verbose_name='创建人ID')),
                ('last_edited_by', models.ForeignKey(blank=True, help_text='最后编辑人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placec_eb', to='user.UserExtension', verbose_name='最后编辑人ID')),
                ('place', models.ForeignKey(blank=True, help_text='帖子（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, to='place.Place', verbose_name='帖子')),
            ],
            options={
                'verbose_name': '地点-用户-收藏',
                'verbose_name_plural': '地点-用户-收藏',
                'unique_together': {('place', 'created_by')},
            },
        ),
    ]
