# Generated by Django 3.0 on 2021-09-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_placecollect_placepraise'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='gaode',
            field=models.CharField(blank=True, help_text='地点词条高德链接（CharField）', max_length=225, verbose_name='地点词条高德链接'),
        ),
        migrations.AddField(
            model_name='place',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='纬度（PositiveIntegerField）', max_digits=30, null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='place',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='经度（PositiveIntegerField）', max_digits=30, null=True, verbose_name='经度'),
        ),
    ]
