# Generated by Django 3.0 on 2021-09-30 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0007_auto_20210929_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placecollect',
            name='place',
            field=models.ForeignKey(blank=True, help_text='地点（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, to='place.Place', verbose_name='地点'),
        ),
        migrations.AlterField(
            model_name='placepraise',
            name='place',
            field=models.ForeignKey(blank=True, help_text='地点（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, to='place.Place', verbose_name='地点'),
        ),
    ]
