# Generated by Django 3.0 on 2021-10-14 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0008_auto_20210930_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placetalk',
            options={'verbose_name': '地点词条评论', 'verbose_name_plural': '地点词条评论'},
        ),
    ]
