# Generated by Django 3.0 on 2021-10-18 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0009_auto_20211014_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placetalk',
            options={'ordering': ['-id'], 'verbose_name': '地点词条评论', 'verbose_name_plural': '地点词条评论'},
        ),
    ]
