# Generated by Django 3.0 on 2021-09-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='show',
            field=models.BooleanField(default=True, help_text='是否公开可见', verbose_name='是否公开可见'),
        ),
    ]
