# Generated by Django 3.0 on 2021-09-30 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210922_1157'),
        ('place', '0008_auto_20210930_1426'),
        ('trip', '0003_tripcollect_trippraise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripcollect',
            name='trip',
            field=models.ForeignKey(blank=True, help_text='行程（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.Trip', verbose_name='行程'),
        ),
        migrations.AlterField(
            model_name='trippraise',
            name='trip',
            field=models.ForeignKey(blank=True, help_text='行程（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.Trip', verbose_name='行程'),
        ),
        migrations.CreateModel(
            name='PlacesInTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(blank=True, help_text='顺序(PositiveIntegerField)', null=True, verbose_name='顺序')),
                ('name', models.CharField(blank=True, help_text='主要事项（CharField）', max_length=225, verbose_name='主要事项')),
                ('desc', models.TextField(blank=True, help_text='备忘（TextField）', verbose_name='备忘')),
                ('theDate', models.DateField(blank=True, help_text='起始日期（DateTimeField）', null=True, verbose_name='起始日期')),
                ('theBegin', models.TimeField(blank=True, help_text='预期起始（DateTimeField）', null=True, verbose_name='预期起始')),
                ('theTime', models.DecimalField(blank=True, decimal_places=1, help_text='预期时长(h)（PositiveIntegerField）', max_digits=10, null=True, verbose_name='预期时长(h)')),
                ('thePay', models.DecimalField(blank=True, decimal_places=1, help_text='预算(元)（PositiveIntegerField）', max_digits=10, null=True, verbose_name='预算(元)')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='创建时间（DateTimeField）', null=True, verbose_name='创建时间')),
                ('last_edited_date', models.DateTimeField(auto_now=True, help_text='最后编辑时间（DateTimeField）', null=True, verbose_name='最后编辑时间')),
                ('deleted', models.CharField(choices=[('0', '未删除'), ('1', '已删除')], default='0', help_text='是否删除（CharField，可选值：0，1）', max_length=1, verbose_name='是否删除')),
                ('created_by', models.ForeignKey(blank=True, help_text='创建人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pit_cb', to='user.UserExtension', verbose_name='创建人ID')),
                ('last_edited_by', models.ForeignKey(blank=True, help_text='最后编辑人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pit_eb', to='user.UserExtension', verbose_name='最后编辑人ID')),
                ('place', models.ForeignKey(blank=True, help_text='地点（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, to='place.Place', verbose_name='地点')),
                ('trip', models.ForeignKey(blank=True, help_text='行程（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.Trip', verbose_name='行程')),
            ],
            options={
                'verbose_name': '行程添加地点',
                'verbose_name_plural': '行程添加地点',
            },
        ),
    ]
