# Generated by Django 3.0 on 2021-09-30 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20210923_0935'),
        ('trip', '0004_auto_20210930_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='img',
            field=models.ForeignKey(blank=True, help_text='封面（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Trip_img', to='files.Images', verbose_name='封面'),
        ),
    ]
