# Generated by Django 3.0 on 2021-10-14 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_trip_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='triptalk',
            options={'verbose_name': '行程评论', 'verbose_name_plural': '行程评论'},
        ),
    ]
