# Generated by Django 3.0 on 2021-09-26 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0002_notice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-id'], 'verbose_name': '公告', 'verbose_name_plural': '公告'},
        ),
    ]
