# Generated by Django 3.0 on 2021-09-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='path',
            field=models.FileField(blank=True, help_text='文件路径（FileField）', null=True, upload_to='files/2021_09', verbose_name='文件路径'),
        ),
        migrations.AlterField(
            model_name='files',
            name='with_models',
            field=models.CharField(default='Blog', help_text='对应模块（CharField）', max_length=60, verbose_name='对应模块'),
        ),
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.ImageField(blank=True, help_text='图片（ImageField）', null=True, upload_to='imgs/2021_09', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='images',
            name='with_models',
            field=models.CharField(default='Blog', help_text='对应模块（CharField）', max_length=60, verbose_name='对应模块'),
        ),
    ]
